### ISSUE TITLE
Error when clicking on lightbulb on navbar

### ISSUE THREAD

**Issue by gdombiak** [mark-bloom/OctoLight_Home-Assistant#3]
**Describe the bug**
>2023-07-07 22:07:42,155 - octoprint.plugins.octolightHA - DEBUG - API REQUEST isLightOn: False
2023-07-07 22:07:42,155 - octoprint.plugins.octolightHA - DEBUG - Running api action toggle
2023-07-07 22:07:42,156 - octoprint.plugins.octolightHA - DEBUG - PRE request. Light state: False, isLightOn: False
2023-07-07 22:07:42,156 - octoprint.plugins.octolightHA - DEBUG - Running toggle_HA_state
2023-07-07 22:07:42,387 - octoprint.server.api - ERROR - Error calling SimpleApiPlugin octolightHA
Traceback (most recent call last):
  File "/home/pi/oprint/lib/python3.9/site-packages/requests/models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.9/json/decoder.py", line 340, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 1 column 4 (char 3)
>
> During handling of the above exception, another exception occurred:
>
> Traceback (most recent call last):
  File "/home/pi/oprint/lib/python3.9/site-packages/octoprint/server/api/__init__.py", line 95, in pluginData
    response = api_plugin.on_api_get(request)
  File "/home/pi/oprint/lib/python3.9/site-packages/octoprint/util/__init__.py", line 1686, in wrapper
    return f(*args, **kwargs)
  File "/home/pi/oprint/lib/python3.9/site-packages/octoprint_octolightHA/__init__.py", line 169, in on_api_get
    self.light_toggle()
  File "/home/pi/oprint/lib/python3.9/site-packages/octoprint_octolightHA/__init__.py", line 153, in light_toggle
    self.light_state = self.toggle_HA_state() # Returns the current state of the light
  File "/home/pi/oprint/lib/python3.9/site-packages/octoprint_octolightHA/__init__.py", line 116, in toggle_HA_state
    status = response.json()[0]['state']
  File "/home/pi/oprint/lib/python3.9/site-packages/requests/models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Extra data: line 1 column 4 (char 3)

**To Reproduce**
Token, entity id and HA URL has been properly configured.

1. Go to OctoPrint homepage
2. Click on lightbulb on navbar
4. See error above

**Expected behavior**

**Screenshots**

**Your software and hardware (please complete the following information):**
 - OctoPrint 1.9.1 Python 3.9.2 OctoPi 1.0.0
 - Browser chrome
 - Plugin version latest

**Additional context**

**Comment by gdombiak** [comment]
Found the root cause for this exception. The URL to HA had a trailing /. I copy/past it without it but somehow it was still there. 

Anyway, the UI could check for trailing / and remove it to prevent this error.

**Comment by atax112** [comment]
> Found the root cause for this exception. The URL to HA had a trailing /. I copy/past it without it but somehow it was still there.
> 
> Anyway, the UI could check for trailing / and remove it to prevent this error.

Hi, did you manage to get the plugin installed and running no issues?

I have installed it but it isnt enabled, have a warning in octoprint that it is not compatible with python?
I was using an older version so I reflashed with the latest release, same error...

Not sure how to proceed...

**Comment by gdombiak** [comment]
Hey @atax112,

I got things working just fine. The error message in OctoPrint's console is misleading. In octoprint.log you can find the real reason for the error you are seeing. The changed suggested [here](https://github.com/mark-bloom/OctoLight_Home-Assistant/pull/1/files) is what you need to do and restart OctoPrint once you made that change.

Good luck,
Gaston

**Comment by atax112** [comment]
> Hey @atax112,
> 
> I got things working just fine. The error message in OctoPrint's console is misleading. In octoprint.log you can find the real reason for the error you are seeing. The changed suggested [here](https://github.com/mark-bloom/OctoLight_Home-Assistant/pull/1/files) is what you need to do and restart OctoPrint once you made that change.
> 
> Good luck,
> Gaston

Many thanks for the quick update, opened an issue and already solved it in the meantime. 

Running the latest octopi/print there was a python compatibility issue.

Had to edit init.py for python 3.9.2 so <4 instead of <3 and install the repo from the local updated zip.

Cheers

**Comment by mark-bloom** [comment]
Please advise if the corrections to v0.0.2 (v0.0.3) have resolved your problem.
All the formatting around space/tabs has been cleared, so ideally the python version check is now correctly identifying as <4 (it is on my personal machine when downloading 0.0.2 through the plugin manager.
v0.0.3 added support for 'switch' entities, my personal version only supported 'light' entities.

**Comment by mark-bloom** [comment]
Assumed to be resolved as multiple issues raised on similar issues.
