### ISSUE TITLE
Installs but stays disabled / Not compatible with Octoprint or underlying python

### ISSUE THREAD

**Issue by atax112** [mark-bloom/OctoLight_Home-Assistant#4]
**Describe the bug**
Installs but stays disabled / Not compatible with Octoprint or underlying python

**To Reproduce**
Install plugin through plugin manager
Cannot enable afterwards / stays disabled

**Expected behavior**
Plugin should work as is after install

**Screenshots**
![image](https://github.com/mark-bloom/OctoLight_Home-Assistant/assets/67806137/f37e736a-3ee3-44e1-bdf5-637ffe307836)
![image](https://github.com/mark-bloom/OctoLight_Home-Assistant/assets/67806137/9eebd903-04a7-4e96-a370-bc4e883384b2)

**Your software and hardware (please complete the following information):**
 - OctoPrint Version 1.9.1
 - OctoPi Version 1.0.0, running on Raspberry Pi 3 Model B Rev 1.2
 - chrome
 - Plugin version [e.g. 0.1.0]

**Additional context**
Ive been running an older install but reflashed just because of this plugin.
So currently running latest Octoprint/Octopi versions on a Pi3B
Upgraded PIP and PIP3 version to latest, running python 3.9.2

from octoprint.log

```
2023-07-08 12:08:41,493 - octoprint.plugin.core - ERROR - Invalid syntax in plugin file of plugin octolightHA
Traceback (most recent call last):
  File "/home/pi/oprint/lib/python3.9/site-packages/octoprint/plugin/core.py", line 800, in _parse_metadata
    return parse_plugin_metadata(self.location)
  File "/home/pi/oprint/lib/python3.9/site-packages/octoprint/plugin/core.py", line 78, in parse_plugin_metadata
    root = ast.parse(f.read(), filename=path)
  File "/usr/lib/python3.9/ast.py", line 50, in parse
    return compile(source, filename, mode, flags,
  File "/home/pi/oprint/lib/python3.9/site-packages/octoprint_octolightHA/__init__.py", line 218
    		 return dict(
    		^
IndentationError: unexpected indent
2023-07-08 12:08:41,496 - octoprint.plugin.core - WARNING - Plugin OctoLight-Home-Assistant (0.0.1) can't be compiled under Python 3.9.2 due to invalid syntax
```

and

`2023-07-08 16:49:39,095 - octoprint.plugin.core - WARNING - Plugin OctoLight-Home-Assistant (0.0.1) is not compatible to Python 3.9.2 (compatibility string: >=2.7,<3).`

**Comment by atax112** [comment]
Solved by downloading the repo, editing :
```
__init__.py
line 235
__plugin_pythoncompat__ = ">=2.7,<4"

```
re-zipping the repo and installing locally from zip through plugin manager.
