### ISSUE TITLE
Plugin disabled under python 3.9

### ISSUE THREAD

**Issue by sergeolkhovik** [mark-bloom/OctoLight_Home-Assistant#6]
Hi! Trying to install and activate plugin in my environment, but it gets disabled after installation:

![image](https://github.com/mark-bloom/OctoLight_Home-Assistant/assets/5941860/321cff6e-8dcf-4d61-be33-f77632aa6366)

I have OrangePi running armbian bullseye:
 - OctoPrint or OctoPi version: 1.9.1
 - Armbian Bullseye (i.e. Debian 11)
 - Python 3.9
 - Plugin version: 0.0.1

Also I checked the logs, I see nothing interesting in plugin_pluginmanager_console.log
```
2023-07-10 22:20:49,795 > Building wheels for collected packages: OctoLight-Home-Assistant
2023-07-10 22:20:49,796 > Building wheel for OctoLight-Home-Assistant (setup.py): started
2023-07-10 22:20:53,036 > Building wheel for OctoLight-Home-Assistant (setup.py): finished with status 'done'
2023-07-10 22:20:53,038 > Created wheel for OctoLight-Home-Assistant: filename=OctoLight_Home_Assistant-0.0.1-py2.py3-none-any.whl size=5948 sha256=95a753166d8c9e0b8897567b66009c62f30d9d45d7c41d515b0cb49da5f32831
2023-07-10 22:20:53,039 > Stored in directory: /tmp/pip-ephem-wheel-cache-k1obgsnn/wheels/52/d9/f5/63807affdc1b58cc36b9b0c57655a98e047e48f5f99dcb8704
2023-07-10 22:20:53,040 > Successfully built OctoLight-Home-Assistant
2023-07-10 22:20:53,042 > Installing collected packages: OctoLight-Home-Assistant
2023-07-10 22:20:53,043 > Successfully installed OctoLight-Home-Assistant-0.0.1
```
But in the main log file I see this:
```
2023-07-10 22:20:55,359 - octoprint.plugins.pluginmanager - INFO - The plugin was installed successfully: OctoLight-Home-Assistant, version 0.0.1
2023-07-10 22:20:55,680 - octoprint.plugins.tracking - INFO - Sent tracking event install_plugin, payload: {'plugin': 'octolightHA', 'plugin_version': '0.0.1'}
2023-07-10 22:23:05,023 - octoprint.server.api.system - INFO - Performing command for core:restart: sudo systemctl restart octoprint.service
2023-07-10 22:23:11,407 - octoprint.startup - INFO - ******************************************************************************
2023-07-10 22:23:11,413 - octoprint.startup - INFO - Starting OctoPrint 1.9.1
2023-07-10 22:23:11,416 - octoprint.startup - INFO - ******************************************************************************
2023-07-10 22:23:12,119 - octoprint.util.connectivity.connectivity_checker - INFO - Connectivity changed from offline to online
2023-07-10 22:23:12,136 - octoprint.util.connectivity.connectivity_checker - INFO - Connectivity state is currently: online
2023-07-10 22:23:12,137 - octoprint.util.connectivity.connectivity_checker - INFO - Connecting to 192.168.113.1:53 is working
2023-07-10 22:23:12,137 - octoprint.util.connectivity.connectivity_checker - INFO - Resolving octoprint.org is working
2023-07-10 22:23:12,575 - octoprint.startup - INFO - Blacklist processing done, adding 3 blacklisted plugin versions: roomtemp (any), GcodeEditor (>=0.1.1,<=0.2.8), gcodeleveling (>=0.1.0,<=0.1.1)
2023-07-10 22:23:12,602 - octoprint.plugin.core - INFO - Loading plugins from /home/octoprint/OctoPrint/lib/python3.9/site-packages/octoprint/plugins, /home/octoprint/.octoprint/plugins and installed plugin packages...
2023-07-10 22:23:18,215 - octoprint.plugin.core - INFO - Plugin Pi Support Plugin (2023.5.24) did not pass check, not loading.
2023-07-10 22:23:18,345 - octoprint.plugin.core - ERROR - Invalid syntax in plugin file of plugin octolightHA
Traceback (most recent call last):
  File "/home/octoprint/OctoPrint/lib/python3.9/site-packages/octoprint/plugin/core.py", line 800, in _parse_metadata
    return parse_plugin_metadata(self.location)
  File "/home/octoprint/OctoPrint/lib/python3.9/site-packages/octoprint/plugin/core.py", line 78, in parse_plugin_metadata
    root = ast.parse(f.read(), filename=path)
  File "/usr/lib/python3.9/ast.py", line 50, in parse
    return compile(source, filename, mode, flags,
  File "/home/octoprint/OctoPrint/lib/python3.9/site-packages/octoprint_octolightHA/__init__.py", line 218
                 return dict(
                ^
IndentationError: unexpected indent
2023-07-10 22:23:18,353 - octoprint.plugin.core - WARNING - Plugin OctoLight-Home-Assistant (0.0.1) can't be compiled under Python 3.9.2 due to invalid syntax
```

Going to build and install python 3.11 and reinstall OctoPrint with 3.11 as 3.9 becomes pretty obsolete, will update if I'll find anything.

**Comment by mark-bloom** [comment]
It appears combinations tabs/spaces was causing the python versions to not read in properly. The latest version through the plugin manager is showing the correct versions. Please advise if this isn't the case for you. 

![image](https://github.com/mark-bloom/OctoLight_Home-Assistant/assets/3166605/97a11c9f-e47c-4328-952c-a47a9143676c)


All the formatting around space/tabs has been unified to spaces and the new version can be downloaded through the plugin manager (it may not update the version number immediately, but if you uninstall and reinstall, it is finding the 0.0.2).

**Comment by sergeolkhovik** [comment]
It works now, thank you!

**Comment by sergeolkhovik** [comment]
One more question, please:

![image](https://github.com/mark-bloom/OctoLight_Home-Assistant/assets/5941860/2b234428-c7ef-4b6a-95e7-3091f8dfcda4)

I see that the icon doesn't reflect the state of light entity (light.d5_light in my case which is a LED on esp32-cam), the button works OK and toggles the light state, but the icon is still the same, like on a screenshot.

Or should I open another issue?

**Comment by mark-bloom** [comment]
If you could please enable the debug logs for the plugin (I will add instructions to the bug report in the next release) and let me know what it says after trying to change the status:

![image](https://github.com/mark-bloom/OctoLight_Home-Assistant/assets/3166605/9b90001a-3bc9-4aac-814a-e5e945c32b1d)

Then download the octoprint.log under settings>logging, and see if there's any debug messages you can provide. That way I can try identify where the issue is.

**Comment by sergeolkhovik** [comment]
Mark, thank you for help with the logging, sure, here it is:

```
2023-08-11 12:26:35,357 - octoprint.plugins.logging - INFO - Setting logger octoprint.plugins.octolightHA level to 10
2023-08-11 12:27:22,096 - octoprint.plugins.octolightHA - DEBUG - API REQUEST isLightOn: False
2023-08-11 12:27:22,097 - octoprint.plugins.octolightHA - DEBUG - Running api action toggle
2023-08-11 12:27:22,098 - octoprint.plugins.octolightHA - DEBUG - PRE request. Light state: False, isLightOn: False
2023-08-11 12:27:22,099 - octoprint.plugins.octolightHA - DEBUG - Running toggle_HA_state
2023-08-11 12:27:22,100 - octoprint.plugins.octolightHA - DEBUG - Running light toggle
2023-08-11 12:27:22,247 - octoprint.server.api - ERROR - Error calling SimpleApiPlugin octolightHA
Traceback (most recent call last):
  File "/home/octoprint/OctoPrint/lib/python3.9/site-packages/octoprint/server/api/__init__.py", line 95, in pluginData
    response = api_plugin.on_api_get(request)
  File "/home/octoprint/OctoPrint/lib/python3.9/site-packages/octoprint/util/__init__.py", line 1686, in wrapper
    return f(*args, **kwargs)
  File "/home/octoprint/OctoPrint/lib/python3.9/site-packages/octoprint_octolightHA/__init__.py", line 216, in on_api_get
    self.light_toggle()
  File "/home/octoprint/OctoPrint/lib/python3.9/site-packages/octoprint_octolightHA/__init__.py", line 200, in light_toggle
    self.light_state = self.toggle_HA_state() # Returns the current state of the light
  File "/home/octoprint/OctoPrint/lib/python3.9/site-packages/octoprint_octolightHA/__init__.py", line 163, in toggle_HA_state
    status = response.json()[0]['state']
IndexError: list index out of range
2023-08-11 12:27:26,697 - octoprint.plugins.octolightHA - DEBUG - API REQUEST isLightOn: False
2023-08-11 12:27:26,699 - octoprint.plugins.octolightHA - DEBUG - Running api action toggle
2023-08-11 12:27:26,699 - octoprint.plugins.octolightHA - DEBUG - PRE request. Light state: False, isLightOn: False
2023-08-11 12:27:26,700 - octoprint.plugins.octolightHA - DEBUG - Running toggle_HA_state
2023-08-11 12:27:26,701 - octoprint.plugins.octolightHA - DEBUG - Running light toggle

```

May be just add dump of that reponse into logging?
I'm not familiar with OctoPrint, but I think something like:
```
response = requests.post(url, headers=headers, data=data, verify=verify_certificate)
self._logger.debug("HA response: {}".format(repr(response)))
```
?

BTW HA is latest (2023.8.1)

**Comment by mark-bloom** [comment]
Yeah there's a bit of a problem that when a function errors out, it doesn't include any of the logging from that function, even before the error. In this instance I don't have a try/except around the `status = response.json()[0]['state']`.

Have you tried the v0.0.3 (just uninstall and reinstall from the plugin manager)? This specific error other people were getting due to it being a 'switch' instead of a 'light' entity. If you're still getting it, I'll make it so that v0.0.4 just never uses that particular POST response, since it seems finicky on whether or not HA actually sends it back.

**Comment by sergeolkhovik** [comment]
Yeah, it works!

![image](https://github.com/mark-bloom/OctoLight_Home-Assistant/assets/5941860/ed4f8048-dc78-4f3c-a2b3-8ecf976b2ccf)


I had 0.0.3 already installed but did uninstall with data clean-up, installed again and provided the same settings and now it works like a charm!
Thanks!
