### ISSUE TITLE
Index out of range when clicking on light bulb

### ISSUE THREAD

**Issue by venator42** [mark-bloom/OctoLight_Home-Assistant#7]
**Describe the bug**
After manually fixing the bug described in #6  I could access the settings and linked the plugin to my homeassistant. I get the following error message in octoprint.log when clicking on the lightbulb:
```
2023-07-27 09:22:33,887 - octoprint.server.api - ERROR - Error calling SimpleApiPlugin octolightHA
Traceback (most recent call last):
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint/server/api/__init__.py", line 95, in pluginData
    response = api_plugin.on_api_get(request)
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint/util/__init__.py", line 1686, in wrapper
    return f(*args, **kwargs)
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint_octolightHA/__init__.py", line 169, in on_api_get
    self.light_toggle()
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint_octolightHA/__init__.py", line 153, in light_toggle
    self.light_state = self.toggle_HA_state() # Returns the current state of the light
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint_octolightHA/__init__.py", line 116, in toggle_HA_state
    status = response.json()[0]['state']
IndexError: list index out of range
```

**To Reproduce**
1. Go to Octoprint Dashboard
2. Click on Lightbulb in the navbar
3. See error in octoprint.log

**Expected behavior**
Light should be turned on.

**Your software and hardware (please complete the following information):**
 - OctoPrint or OctoPi version: 1.9.2
 - Browser: Firefox 114.0.2
 - Plugin version: 0.0.1

**Additional context**
Entity-ID Type (just in case that this matters): switch

**Comment by mark-bloom** [comment]
Please advise if the corrections to v0.0.2 (now available through the plugin manager) have resolved your problem.

**Comment by venator42** [comment]
Unfortunately the problem persists.

**Comment by mark-bloom** [comment]
It probably then relates to the entity type. Currently the program supports the 'light' entity type, and the expected JSON responses.

I will try and work on enabling support for different device types but I'm unsure how long that will take.

**Comment by venator42** [comment]
I tested it with two different light entities and it works as expected.

**Comment by mark-bloom** [comment]
Let me know if v0.0.3 resolves this issue with your switch entity. The update is intended to provide support to both 'light' and 'switch' entities.

**Comment by venator42** [comment]
It works. :) Thank you
